### ISSUE TITLE
Obtain Go Bible source code from CrossWire SVN

### ISSUE THREAD

**Issue by DavidHaslam** [DavidHaslam/GoBibleCore#1]
As CrossWire is no longer actively developing Go Bible, the latest version of the source code still in our SVN repository should be copied to GitHub so that is more readily accessible.

**Comment by DavidHaslam** [comment]
Thanks to @mats-claassen - this issue can now be closed.

**Comment by mats-claassen** [comment]
@DavidHaslam There is one file (MultiFileBibleSource) which was not in the SVN repository, so I would think they deleted it. Still I kept it here. 

For the section headings, I only supported CombinedChapterBibleSource,. I think the two files are different ways GoBibleCore receives the Bible information.

I guess if they deleted it in SVN then it probably won't work anymore and we can delete it here as well, unless we know of someone who actually uses that format.

What do you think? File would still be in the history

**Comment by DavidHaslam** [comment]
I was not involved in the fine details of code development.

My role as Go Bible project leader was more of a co-ordination and management one.

My technical involvement wasn't insignificant. 

A lot of details about how things should work were discussed with the various code developers.
